### ISSUE TITLE
WooCommerce Sequential Order Numbers

### ISSUE THREAD

**Issue by rajatsingh828** [parsakafi/wp-telegram-pro#3]
Hey , I have been using your Plugin for Many Months now :) 

its so easy to integrate and use but still have many changes remaining 

I am having problems with plugin :- WooCommerce Sequential Order Numbers

the plugin changes number by incrementing it by +1 rather than default but Wp telegram pro shows woocommerce order number even when sequential order numbers are on.

wish you did update through GitHub.
would be supporting a ton

**Comment by parsakafi** [comment]
Hello
Thanks for supporting 

Develop WP Telegram Pro plugin stopped.
And I want to release plugin with a new name.

Can you explain more about your problem?
I don't understand.

This is your plugin used?
https://wordpress.org/plugins/woocommerce-sequential-order-numbers/

Where exactly is this problem affecting?

**Comment by rajatsingh828** [comment]
Thank you for replying , do notify when you release new plugin 

also yes thats the plugin

My issue is :- 

Example :- Order id was 13210 as woocommerce default and plugin showed correct message as 13210 

but as i downloaded that plugin and installed , the next order id came up as 13211 but plugin showed as 13213 , i doubled checked it but the error was same for next orders too. like 13212 for 13220 something.

**Comment by rajatsingh828** [comment]
Hey , looks like plugin is not working anymore for users maybe due to changes from telegram but still able to receive messages from wordpress / woocommerce 

i am waiting for your new plugin sir 😢

**Comment by parsakafi** [comment]
Hello
New version released with a new name, Teligro
https://wordpress.org/plugins/teligro

If you have any problem please create issue in Teligro repository
github.com/teligro/teligro
